<div class='textsmall' align='justify'>
<center>
<strong>A Wake-Up Call for America's Jews</strong>
<br>
By Aisha Siddiqa Qureshi
</center>
<p>
Help let the world know that you are here to stay. With a homeland, your survival is guaranteed; without one, your own lives are also on the line.
<p>
Dear Jews, everywhere, I would like to point out the time bomb likely to explode in your faces. It has already been detonated in France. When it happens in the country you call home, you may be shocked and unprepared, so I present this letter to you as a warning. In it, I will inform you of some basic facts - facts that can never be changed.
<p>
1. You are a Jew, whether you like it or not.
<p>
It doesn't matter if you change your name. It doesn't matter if you convert. You say you don't think of yourself as Jewish? Perhaps Judaism is just too far beneath your enlightened consciousness. Well tough luck - it's still a part of who you are. I know, I know, this is the modern world.
In America, Jews are first class citizens. But it really is "only in America" where Jews enjoy equal status. Perhaps you have forgotten that with the exception of the United States and Israel, Jews in all other countries
suffer the stigma of the outsider. Granted that your personal future looks bright since you overcame your ancestry, however, you mistakenly believe that you are a member of the elite club of secular society.
But, have you ever heard of the Holocaust? A little over 60 years ago, the discovery of one Jewish grandparent in one's family tree was enough to mark
that person for the slaughter. That means that Jews living the high life in denial were plucked from their exalted status and plunged into the
concentration camps and worse. And in the centuries and decades prior to the Holocaust, was life more secure? At certain periods, indeed it was - or so
it seemed - and then, the inevitable fall from grace. You have become used to being accepted. But, if you forget the stories of
your ancestors, you are sure to see them come true in your own lives. Please believe me. Being a Muslim, living under the dark shadows of Islamism, I
see, watch and experience every day the reach and depth of anti-Semitism that has taken hostage a whole people. There cannot be a better person than
a Muslim to warn you of your misguided sense of liberalism; I live in an environment that is so carefully and skillfully prepared to annihilate Jews.
Note the rising anti-Semitism in Europe and in certain sectors of American society (college campuses, the media, the Presbyterian Church etc.) Just a
few weeks ago, 200 French Jews immigrated to Israel, fed up with the rampant persecution by "Muslim toughs," as former New York City Mayor, Edward I.
Koch puts it. The country which has pledged "Libert», Egalit», Fraternit»" since the 1800s once again turned its back on the Jews. "Never again" is the
oath the Jewish people have collectively sworn since the horrors of World War II. All freedom loving peoples of the world must actively participate in
securing Jewish future to guarantee that this oath holds true. Jews truly are the chosen people - when things in the world go sour, Jews are chosen
to pay the penalty. 
<p>
2. The world has hated and will always hate Jews for one reason.
<p>
Over the summer a friend of mine attended a lecture in Israel given by Rabbi Eric Coopersmith of Aish Ha Torah, entitled "Why the Jews?" He told me that
Rabbi Eric disproved the common misconceptions of why the Jews are always picked on and got to the truth of the matter. It isn't because the Jews
supposedly control the world and all the money in it (you don't), or because you killed Jesus (you didn't), or because you just happen to always be 
the scapegoat. I agree with Rabbi Coopersmith who pointed out that you can only scapegoat a group of people you were already willing to hate. His 
humorous example was that the Nazis couldn't scapegoat midgets and it's true - it would never work. Whether they realize it or not, people are and have
always been willing to hate the Jews for one simple reason: they gave the world the concept of an objective right and wrong.
When the first seeds of Judaism were planted in Abraham, his descendents were required to teach humanity about conscience and morality. In a time of 
universal barbarism and cruelty, the ancient Hebrews were the first to adopt for themselves the six values essential for civilized existence: the
sanctity of life, education, family, social responsibility, equality before the law, and peace (Source: WorldPerfect by Ken Spiro). In my view, the
ancient world couldn't forgive you for it and neither could Hitler. In his writings, Hitler clearly said that he is a barbarian who wants to express
his primal instincts and Judaism says he can't. For him, not only is the concept of conscience "a Jewish invention; it is a blemish, like
circumcision." The infamous Hitler Youth even sang a song with these lyrics:
<p>
We are the joyous Hitler Youth;<br>
We have no need for Christian virtue.<br>
Our leader is our savior;<br>
The pope and rabbi shall be gone.<br>
We shall be pagans once again.
<p>
Hitler also told his people that Providence has ordained that I should be the greatest liberator of humanity. I am freeing man from the restraints of
an intelligence that has taken charge, from the dirty and degrading self-mortifications of a false vision known as conscience and morality, and
from the demands of a freedom and personal independence which only a very few can bear.
<p>
Visit <a href="http://www.aish.com/seminars/whythejews/wtj01000.htm">http://www.aish.com/seminars/whythejews/wtj01000.htm</a> for the full seminar.
<p>
Yes, even though Hitler is Hitler and he was no liberal, the comparison matters because liberal America and Europe are slowly rebelling against the
values required for civilized existence. These are the values advanced in the Jewish Bible, specifically the Torah, and summed up in the 10
Commandments. These values were offered - though hardly accepted - to all of humanity through the vehicles of Judaism and Christianity. But, liberals,
either through base ignorance or intention, are rejecting those values in word and deed. Example: a deaf lesbian couple genetically engineered two
deaf children on purpose! If you don't see what is wrong with that - how selfish and cruel it is for parents to deliberately handicap children they
supposedly love and are required to care for - then I've made my point. You have abandoned the notion of objective morality, feeling that it stifles
your freedom of action. You have become a barbarian that feels he can do whatever he wants and, like Hitler, is proud of it.
<p>
3. You can't have your cake and eat it too. And if you lose your cake, there's nothing to eat.
<p>
I really like animals and I really care about the environment. I am also in favor of women's rights. But you know what? None of it matters. "Yes it does
matter!" I can hear you thinking. But here's my answer: we have bigger problems! Civilization as we know it is in jeopardy because liberals are so
eager to abandon the values on which it rests. They are not willing to support the institutions that safeguard those values. Case in point: radical
Islam threatens to subjugate the world and murder, enslave or convert all non-Muslims. Liberals are not even willing to support the institution most
necessary for our defense against radical Islam: the military. Instead, they blame America. To them, America is the immoral bully. Likewise, Israel is another immoral
bully that liberals are reluctant to support. But in actuality, Israel has been a victim of Islamist terrorism since the 1920s, long before the state
was established. The same terrorism is now being waged worldwide, even against countries, like Saudi Arabia, that sponsor it! Israel is on the
front lines of Islamist terrorism and Americans, especially American Jews, should support it. Liberals undercut American efforts and damage the morale
of our troops by questioning the war while it is being waged! Some say the war is a mistake, that it is just a pompous show of American imperialism.
Others go as far as to claim that we are fighting an enemy of our own invention, denying Saddam Hussein's link to global terrorism, and assuming
that just because WMDs have not been discovered yet, they do not exist.
<p>
My friends, after 9/11, how can you possibly assert that war against Islamist terrorism is unjustified? Should we trust the terrorist supporters
who, in English, deny that they are waging global jihad against the civilized world, yet say it outright in their own language? Liberals would
rather trust Saddam than our own president. Israel's fight is civilization's fight and we must support it before the same unremitting terror comes to our
own shores. We must show that we are willing to fight and expect to win.
<p>
Liberals criticize the United States for not involving the U.N. in its war on terror. But if you care about Israel, why would you want the U.S. to
empower an institution that is corrupt, anti-Semitic, and anti-Zionist?
<p>
I know a lot of liberal Jews who support Israel. Here's what I say to them - they can just give themselves a big old pat on the back because that's
really all they're going to get from anyone. In other words, there's nothing to be gained by voting for Kerry with respect to Israel but I'll tell you
what you risk losing: our "cake" - Israel.
<p>
As a liberal Jew, you think that by voting as a democrat you will save the earth and all its peaceful creatures, and by some crazy extension, Israel's
survival will somehow be guaranteed. You don't believe that war solves anything and neither does your presidential candidate. You and Kerry believe
that diplomacy and appeasement will protect Israel, even while its Arab enemies send in suicide bombers to kill civilians, and launch mortar and
rocket attacks on schools, synagogues, and hospitals. Right?
<p>
Wrong. To quote the guys at Protest Warrior (www.protestwarrior.com) 
<p>
"Except for ending slavery, Fascism, Nazism, and Communism, war has never solved anything!" You may want peace - and believe me, so do I - but do you
know who doesn't want peace? Arafat, Saddam, Bin Laden, and all their brainwashed followers - the illiterate as well as the many literate ones -
who blame America and Israel for their problems instead of their self-indulgent, sadistic dictators. Okay, they actually do want peace, but
all of infidels have to convert to Islam first. That's not going to work for anyone who believes in truth and justice. We can pretend that our enemies
share our values and see the world the same way we see it, but the truth still remains - they won't budge from their positions, forcing us to act as
appeasers in an ever futile attempt to win their favor.
<p>
To paraphrase Daniel Pipes, appeasement doesn't work against ideologically driven opponents. They see it as a show of weakness and hence, a victory for
themselves. It didn't work with Nazis and it's not going to work with our enemies of today either. We can't make peace with people who don't want
peace. And if they say they want peace, we need to evaluate their actions before we blindly accept their words as gospel, as we have so many times in the past.
<p>
Speaking of empty words and promises, don't be duped by the 2004 election propaganda from either party. So when the Kerry-Edwards "Greetings from the
Jewish Outreach Team" tells you that John Kerry plans to wean America off its dependence on the Saudis, don't buy it. Don't assume that Kerry's the
better candidate believing that he, unlike Bush, is not in bed with the Saudis. Folks, the bed is a lot bigger than you think, and there's plenty of
space taken up by Kerry. Sure, George W. Bush is no George Washington but that doesn't automatically make Kerry Abe Lincoln. Translation: we must vote
for the lesser of two evils.
<p>
The Saudis will be tied up with our government no matter who wins (source: Sleeping with the Devil by Robert Baer), which makes the entire subject of
Saudi dependence a non-issue. In the words of Dr. Jack Wheeler, "The American game of life is poker. All of us are in the highest-stakes game of
our lives right now and the only way to back out is to leave the table - leave America and move somewhere else. If you're staying put, then you're in
the game, and you play the hand you're dealt.
<p>
There is absolutely no escaping from this reality: either John Kerry or George Bush will be elected President of the United States this November."
But wait! If you're a Jew, how can you possibly support the religious Right which seeks to convert you? Here's my response. First, I feel much more
comfortable supporting a party that is based on JUDEO-Christian VALUES. Look guys - values! Second, they've been trying to convert the Jews for over 2000
years. Has it worked? No it hasn't - you are still here. Third, they may want to convert you, but at least they don't want to slice off our heads and
parade around holding our body parts. Your real enemies have done more than just taunt you with their master plan. You have seen the plan and how it
works. Why are you not more shaken by that?
<p>
So you may love your live minks and your trees and trust me, I'm happy for your diverse, non-discriminating family, but at the end of the day you're
still a Jew, remember? And if you've ever taken the time to stroll through history, you'd know that the one thing that makes Jews of today so much more
privileged than Jews of the past is the fact that you have a state.
<p>
When France, or Germany, or God forbid, America doesn't want you anymore, Israel will take you in. Can you imagine being told you have a matter of
days to leave your home and you have nowhere to go? A Jewish friend of mine says, she certainly can't imagine it but her great-grandparents were there.
It was a time when there was no Israel and America had already closed her gates - the fact that her grandmother and her parents were admitted to this
country is nothing short of miraculous. The rest of their family wasn't so fortunate.
<p>
I beg of you, put your vanities aside and for the sake of your children, let's make sure they have somewhere to go. Your real protection is there, in
the heart of the Middle East, surrounded by twenty-two Arab nations that all want to devour it. It's there, and it's your, but more often than not,
Israel's very existence is dangling by a thread. That was the case in 1948, 1967, 1973, and countless other times, including now - 2004. You have no
time to waste. Help let the world know that you are here to stay. With a homeland, your survival is guaranteed; without one, your own lives are also
on the line. You can assimilate as much as you want but that doesn't change your inherent Jewish blood and DNA.
<p>
The Jew-haters of the world want to eradicate every trace of you. They will not be satisfied by simply watering you down. That was Hitler's belief.
Radical Muslim enemies share his goal and are attempting to carry out his plan. Bush understands their end-game. Do you?
