<table width="700" border="0" cellspacing="0" cellpadding="0">
          <tr> 
            <td><img src="images/layout2_hor1a.jpg" width="325" height="88"></td>
            <td><img src="images/layout2_hor1b.jpg" width="375" height="88" border="0" usemap="#Map" href="leisure.php"></td>
          </tr>
          <tr> 
            <td colspan="2"><img src="images/layout2_hor2.jpg" width="700" height="19" border="0" usemap="#Map2"></td>
          </tr>
        </table>