<map name="Map">
  <area shape="rect" coords="41,1,123,24" href="index.htm">
  <area shape="rect" coords="124,1,207,25" href="career.php">
  <area shape="rect" coords="207,1,292,25" href="financial.php">
  <area shape="rect" coords="292,1,374,25" href="leisure.php">
</map>
<map name="Map2">
  <area shape="rect" coords="197,2,325,29" href="share_advice.php">
  <area shape="rect" coords="333,2,461,57" href="advertise.php">
  <area shape="rect" coords="469,3,534,47" href="partners.php">
  <area shape="rect" coords="541,3,609,88" href="about_us.php">
  <area shape="rect" coords="616,2,710,89" href="contact_us.php">
</map>