<script language="JavaScript" type="text/JavaScript">
<!--
function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_changeProp(objName,x,theProp,theValue) { //v6.0
  var obj = MM_findObj(objName);
  if (obj && (theProp.indexOf("style.")==-1 || obj.style)){
    if (theValue == true || theValue == false)
      eval("obj."+theProp+"="+theValue);
    else eval("obj."+theProp+"='"+theValue+"'");
  }
}
//-->
</script>

<table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center">
			<div class="desc" id="empty" style="display:block"><font color=white>---</font></div>
			<div class="desc" id="biography" style="display:none">Read about my past, including where I am from and what schools I have attended.</div>
			<div class="desc" id="personal" style="display:none">Visit friends' websites, read interesting articles, and get internet tips.</div>
			<div class="desc" id="professional" style="display:none">View or download my resume.</div>
			<div class="desc" id="photos" style="display:none">Check out photos of myself and the people in my life.</div>
			<div class="desc" id="contact" style="display:none">If you need to get a hold of me, email is the best way to go.</div>
		</td>
	</tr>
</table>
<table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr> 
      <td colspan="2"><img src="header_1.jpg" width="600" height="20"></td>
    </tr>
  </table>
  <table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr> 
      <td width="9"><img src="header_3.jpg" width="16" height="25"></td>
      <td width="591" class="nav"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr class="nav"> 
            <td width="20%"><div align="center" onMouseOver="MM_changeProp('biography','','style.display','block','DIV');MM_changeProp('empty','','style.display','none','DIV')" onMouseOut="MM_changeProp('biography','','style.display','none','DIV');MM_changeProp('empty','','style.display','block','DIV')"><a href="biography.php">biography</a></div></td>
            <td width="20%"><div align="center" onMouseOver="MM_changeProp('personal','','style.display','block','DIV');MM_changeProp('empty','','style.display','none','DIV')" onMouseOut="MM_changeProp('personal','','style.display','none','DIV');MM_changeProp('empty','','style.display','block','DIV')"><a href="personal.php">personal</a></div></td>
            <td width="20%"><div align="center" onMouseOver="MM_changeProp('professional','','style.display','block','DIV');MM_changeProp('empty','','style.display','none','DIV')" onMouseOut="MM_changeProp('professional','','style.display','none','DIV');MM_changeProp('empty','','style.display','block','DIV')"><a href="professional.php">professional</a></div></td>
            <td width="20%"><div align="center" onMouseOver="MM_changeProp('photos','','style.display','block','DIV');MM_changeProp('empty','','style.display','none','DIV')" onMouseOut="MM_changeProp('photos','','style.display','none','DIV');MM_changeProp('empty','','style.display','block','DIV')"><a href="photos.php">photo gallery</a></div></td>
            <td width="20%"><div align="center" onMouseOver="MM_changeProp('contact','','style.display','block','DIV');MM_changeProp('empty','','style.display','none','DIV')" onMouseOut="MM_changeProp('contact','','style.display','none','DIV');MM_changeProp('empty','','style.display','block','DIV')"><a href="contact.php">contact 
                info.</a></div></td>
          </tr>
        </table></td>
      <td width="9" class="nav"><img src="header_5.jpg" width="16" height="25"></td>
    </tr>
  </table>
  <table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr> 
      <td colspan="2"><img src="header_2.jpg" width="600" height="5"></td>
    </tr>
  </table>