<table width="100%" border="0" cellspacing="3" cellpadding="15">
                  <tr bgcolor="#F4F4F4"> 
                    <td width="50%"><div align="center"><span class="text"><a href="photos/Artem_BW.JPG"><img src="photos/Artem_BW.JPG" width="100" height="133" border="0"></a></span></div></td>
                    <td width="50%"><div align="center"><span class="text"><a href="photos/Zapor.jpg"><img src="photos/Zapor.jpg" width="100" height="60" border="0"></a></span></div></td>
                  </tr>
                  <tr bgcolor="#F4F4F4"> 
                    <td><div align="center"><a href="photos/Sentra.JPG"><img src="photos/Sentra.JPG" width="100" height="75" border="0"></a></div></td>
                    <td><div align="center"><a href="photos/Camping_2004.jpg"><img src="photos/Camping_2004.jpg" width="100" height="69" border="0"></a></div></td>
                  </tr>
                </table>