<table width="100%" border="0" cellspacing="3" cellpadding="15">
                  <tr bgcolor="#F4F4F4"> 
                    <td width="50%"><div align="center"><span class="text"><a href="photos/2005fleetweek/IMG_0380.JPG"><img src="photos/2005fleetweek/IMG_0380.JPG" width="100" height="74" border="0"></a></span></div></td>
                    <td width="50%"><div align="center"><span class="text"><a href="photos/2005fleetweek/IMG_0400.JPG"><img src="photos/2005fleetweek/IMG_0400.JPG" width="100" height="74" border="0"></a></span></div></td>
                  </tr>
                  <tr bgcolor="#F4F4F4"> 
                    <td><div align="center"><span class="text"><a href="photos/2005fleetweek/IMG_0387.JPG"><img src="photos/2005fleetweek/IMG_0387.JPG" width="100" height="74" border="0"></a></span></div></td>
                    <td><div align="center"><span class="text"><a href="photos/2005fleetweek/IMG_0396.JPG"><img src="photos/2005fleetweek/IMG_0396.JPG" width="100" height="74" border="0"></a></span></div></td>
                  </tr>
                </table>