<table width="702" border="0" cellpadding="0" cellspacing="0" bgcolor="#000000">
    <tr> 
      <td><img src="images/black_line.jpg" width="701" height="1"></td>
    </tr>
    <tr> 
      <td><table width="700" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr bgcolor="#000000" class="navbar"> 
            <td width="50%"><div align="center" id="copyrights" onMouseOver="MM_changeProp('copyrights','','style.backgroundColor','orange','DIV')" onMouseOut="MM_changeProp('copyrights','','style.backgroundColor','black','DIV')"><a href="#"><font color="#FFFFFF">copyrights</font></a></div></td>
            <td width="50%"><div align="center" id="disclaimer" onMouseOver="MM_changeProp('disclaimer','','style.backgroundColor','red','DIV')" onMouseOut="MM_changeProp('disclaimer','','style.backgroundColor','black','DIV')"><a href="#"><font color="#FFFFFF">disclaimer</font></a></div></td>
          </tr>
        </table></td>
    </tr>
    <tr>
      <td><img src="images/black_line.jpg" width="701" height="1"></td>
    </tr>
  </table>