<table width="100%" border="0" cellpadding="0" cellspacing="0">
                      <tr> 
                        <td>
							&nbsp;																	
						</td>
                      </tr>
                      <tr> 
                        <td>
							<img src="images/black_line.jpg" width="140" height="1">																	
						</td>
                      </tr>
                      <tr class="textsmall" bgcolor='#999999'> 
                        <td>
							<div align="center">
								<strong>Conflict Areas</strong>																	
							</div>
						</td>
                      </tr>
                      <tr> 
                        <td>
							<img src="images/black_line.jpg" width="140" height="1">																	
						</td>
                      </tr>
</table>					
<table width="139" border="0" cellpadding="0" cellspacing="0">
					  <tr bgcolor='#E1E1E1'>
					  	<td align='right' class='textsmall'>
							<div id="usa" onMouseOver="MM_changeProp('usa','','style.backgroundColor','#F2F2F2','DIV')" onMouseOut="MM_changeProp('usa','','style.backgroundColor','#E1E1E1','DIV')"><a href="conflicts.php?id=usa">U.S.A.&nbsp;&nbsp;</a></div>
						</td>
					  </tr>
					  <tr bgcolor='#E1E1E1'>
					  	<td align='right' class='textsmall'>
							<div id="mideast" onMouseOver="MM_changeProp('mideast','','style.backgroundColor','#F2F2F2','DIV')" onMouseOut="MM_changeProp('mideast','','style.backgroundColor','#E1E1E1','DIV')"><a href="conflicts.php?id=me">Middle East&nbsp;&nbsp;</a></div>
						</td>
					  </tr>
					  <tr bgcolor='#E1E1E1'>
					  	<td align='right' class='textsmall'>
							<div id="rusfed" onMouseOver="MM_changeProp('rusfed','','style.backgroundColor','#F2F2F2','DIV')" onMouseOut="MM_changeProp('rusfed','','style.backgroundColor','#E1E1E1','DIV')"><a href="conflicts.php?id=rf">Russian Federation&nbsp;&nbsp;</a></div>
						</td>
					  </tr>					  					  
</table>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
                      <tr> 
                        <td>
							<img src="images/black_line.jpg" width="140" height="1">																	
						</td>
                      </tr>
</table>