<table width="700" border="0" cellspacing="0" cellpadding="0">
		  <tr> 
      		<td colspan=8><img src="images/black_line.jpg" width="700" height="1"></td>
		  </tr>
                <tr class="navbar"> 
                  <td width="12%"><div align="center" id="main" onMouseOver="MM_changeProp('main','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('main','','style.backgroundColor','black','DIV')"><a href="index.php"><font color="#FFFFFF">main</font></a></div></td>
				  <td width="12%"><div align="center" id="news" onMouseOver="MM_changeProp('news','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('news','','style.backgroundColor','black','DIV')"><a href="news.php"><font color="#FFFFFF">news</font></a></div></td>
                  <td width="12%"><div align="center" id="opinions" onMouseOver="MM_changeProp('opinions','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('opinions','','style.backgroundColor','black','DIV')"><a href="opinions.php"><font color="#FFFFFF">opinions</font></a></div></td>
                  <td width="12%"><div align="center" id="events" onMouseOver="MM_changeProp('events','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('events','','style.backgroundColor','black','DIV')"><a href="events.php"><font color="#FFFFFF">events</font></a></div></td>
				  <td width="12%"><div align="center" id="forum" onMouseOver="MM_changeProp('forum','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('forum','','style.backgroundColor','black','DIV')"><a href="http://pub47.bravenet.com/forum/4009505500"><font color="#FFFFFF">forum</font></a></div></td>
				  <td width="12%"><div align="center" id="gear" onMouseOver="MM_changeProp('gear','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('gear','','style.backgroundColor','black','DIV')"><a href="gear.php"><font color="#FFFFFF">gear</font></a></div></td>
                  <td width="12%"><div align="center" id="about" onMouseOver="MM_changeProp('about','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('about','','style.backgroundColor','black','DIV')"><a href="about.php"><font color="#FFFFFF">about</font></a></div></td>
                  <td width="12%"><div align="center" id="contact" onMouseOver="MM_changeProp('contact','','style.backgroundColor','#6699CC','DIV')" onMouseOut="MM_changeProp('contact','','style.backgroundColor','black','DIV')"><a href="contact.php"><font color="#FFFFFF">contact</font></a></div></td>
                </tr>
</table>