<table width="100%" border="0" cellpadding="5" cellspacing="0" class="text">
                      <tr> 
                        <td class="textsmall"><div align="center"><a href="http://www.moscowhelp.org/" target="_blank"><strong><font color="#990000"><img src="images/updates/Beslan.jpg" width="125" height="170" border="0"><br>
                            Donate to help the children of Beslan!</font></strong></a></div></td>
                      </tr>
                    </table>