	 <table width="100%" border="0" cellspacing="1" cellpadding="0">
          <tr> 
            <td>&nbsp;&nbsp;&nbsp;</td>
          </tr>
          <tr> 
           <td bgcolor="#000000">&nbsp;&nbsp;&nbsp;
	    <a href='index.php'><font class='nav'>The Main Page</font></a>
	   </td>
          </tr>
          <tr> 
           <td bgcolor="#000000">&nbsp;&nbsp;&nbsp;
	    <a href='players.php'><font class='nav'>The Players</font></a>
	   </td>
          </tr>
          <tr> 
           <td bgcolor="#000000">&nbsp;&nbsp;&nbsp;
	    <a href='rules.php'><font class='nav'>The Rules</font></a>
	   </td>
          </tr>
          <tr> 
           <td bgcolor="#000000">&nbsp;&nbsp;&nbsp;
	    <a href='games.php'><font class='nav'>The Games</font></a>
	   </td>
          </tr>
          <tr> 
            <td bgcolor="#000000">&nbsp;&nbsp;&nbsp;
	     <a href='contact.php'><font class='nav'>The Contact Info.</font></a>
	    </td>
          </tr>
        </table>